### ISSUE TITLE
Bug with user's name

### ISSUE THREAD

**Issue by treyhuffine** [algolia/github-awesome-autocomplete#55] opened 2017-09-08 16:04 UTC
Huge fan of this! I've been playing around with it and noticed that some people's names are showing up incorrectly. For example, I search for "Paul Irish" who is one of the most followed people on GitHub, and his name showed up as "DevTools Bot".

<img width="352" alt="screen shot 2017-09-08 at 9 02 17 am" src="https://user-images.githubusercontent.com/11709986/30220535-9c31aea0-9474-11e7-89f6-d9921f574b11.png">

**Comment by Haroenv** [comment] 2017-09-08 16:06
I can reproduce this, something must have gone odd with the crawler

**Comment by Shipow** [comment] 2017-09-10 13:32
know bug but we don't know how to fix it yet :/

**Comment by treyhuffine** [comment] 2017-09-11 00:56
Thanks for confirming @Shipow

**Comment by redox** [comment] 2017-09-11 06:29
Hey everyone, sorry for the delay on my side.

I confirm this is an encoding bug githubarchive.org was experiencing at some point. We cannot do much on our side (since we're only consuming that API), but hope more recent data might override it.

**Comment by treyhuffine** [comment] 2017-09-20 01:28
Thanks for tracking that down @redox. Do you know if they're aware? I can try to message them if needed.

**Comment by redox** [comment] 2017-09-20 08:33
> Thanks for tracking that down @redox. Do you know if they're aware? I can try to message them if needed.

They are; I originally opened https://github.com/igrigorik/githubarchive.org/issues/60 and the new endpoint is now working OK. But in order to fix wrongly encoded data from the past, we expect the new endpoint to override it (which should be the case as soon as we have events on a specific user/repo)

**Comment by treyhuffine** [comment] 2017-09-20 16:09
Cool, thank you! Awesome to hear.

**Comment by redox** [comment] 2017-09-20 16:12
You're welcome; will close this issue in the meantime.

**Closed by redox** 2017-09-20 16:12 UTC
Labels: bug
