### ISSUE TITLE
star count Is not correct

### ISSUE THREAD

**Issue by amjunliang** [algolia/github-awesome-autocomplete#73] opened 2017-12-17 08:45 UTC
Is not correct

**Comment by Shipow** [comment] 2017-12-17 11:06
As we are indexing the activity stream of github, the star count should be updated with any new commit on the repo. Do you have a precise project where the delta is important?

**Comment by rayrutjes** [comment] 2017-12-17 11:13
This is a duplicate of #31 .

We will try to fix this, but it is not trivial given we rely on https://www.githubarchive.org/.

**Closed by rayrutjes** 2017-12-17 11:13 UTC
