### ISSUE TITLE
Encode problem with chinese description

### ISSUE THREAD

**Issue by sorrycc** [algolia/github-awesome-autocomplete#15] opened 2015-01-22 02:17 UTC
![image](https://cloud.githubusercontent.com/assets/35128/5849360/ce041dd6-a21f-11e4-9674-fa017727c52f.png)

**Comment by redox** [comment] 2015-01-22 05:43
Hey @sorrycc, thank you for reporting us that. It's actually a bug in the underlying database we're using to feed the the Algolia index :/ I'll close this one since it's a duplicate of https://github.com/algolia/github-awesome-autocomplete/issues/10

**Closed by redox** 2015-01-22 05:43 UTC
Labels: duplicate
